products = [
  {
    "id": 1,
    "name":"Airpods Wireless Bluetooth Headphones",
    "image":"/images/portfolio-7.jpg",
    "disciption":"Bluetooth technology lets you connect it with compatible devices wirelessly High-quality",
    "brand":"Apple",
    "category":"Electronics",
    "price":89.99,
    "countInStock":10,
    "rating":4.5,
    "numReviews":12,
  },
  {
    "id": 2,
    "name":"Iphone 11 Pro 256GB Memory",
    "image":"/images/portfolio-4.jpg",
    "disciption":"Bluetooth technology lets you connect it with compatible devices wirelessly High-quality",
    "brand":"Apple",
    "category":"Electronics",
    "price":89.99,
    "countInStock":10,
    "rating":4.5,
    "numReviews":12,
  },
  {
    "id": 3,
    "name":"Cannon Eos 80D Dslr Camera",
    "image":"/images/portfolio-8.jpg",
    "disciption":"Bluetooth technology lets you connect it with compatible devices wirelessly High-quality",
    "brand":"Apple",
    "category":"Electronics",
    "price":89.99,
    "countInStock":10,
    "rating":4.5,
    "numReviews":12,
  },
  {
    "id": 4,
    "name":"Sony PlayStation 4 Pro White Version",
    "image":"/images/portfolio-9.jpg",
    "disciption":"Bluetooth technology lets you connect it with compatible devices wirelessly High-quality",
    "brand":"Apple",
    "category":"Electronics",
    "price":89.99,
    "countInStock":10,
    "rating":4.5,
    "numReviews":12,
  },
]