# Generated by Django 4.1.3 on 2023-02-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_shippinaddress_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderItems', to='base.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('CLOTHS', 'CL'), ('SHOES', 'SH'), ('BAGS', 'BA'), ('WATCHES', 'WA'), ('ELECTRONICS', 'EL')], max_length=200),
        ),
        migrations.AlterField(
            model_name='shippinaddress',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='base.order'),
        ),
    ]
